updated logic and text coloring

diff --git a/trap-shell b/trap-shell
--- a/trap-shell
+++ b/trap-shell
@@ -1,9 +1,7 @@
 #!/bin/bash
 
-# Trap SIGINT (Ctrl-C) and do nothing when it is received
-trap '' SIGINT
-# Trap SIGTSTP (Ctrl+Z) and do nothing when it is received
-# trap '' SIGTSTP
+
+trap "echo -e '\e[31mNice try!\e[0m'" SIGINT SIGTERM SIGTSTP
 
 echo -e "You have fallen for my trap, how will you get out of here now?"
 
@@ -12,32 +10,24 @@ while true; do
 
 
     if [[ "$line" == "PLEASE GET ME OUT OF HERE" ]]; then
-        echo "Fine >:(, but first, let's play Rock, Paper, Scissors! Think fast!"
+        echo "Fine >:( but first, let's play Rock, Paper, Scissors! Think fast!"
 
         while true; do
 	    
 
-            #countdown=5
-            #while [ $countdown -gt 0 ]; do
-                
-             #   sleep 1
-              #  countdown=$((countdown - 1))
-            #done
-
-
             # Read user input
-            echo -n "Enter your move (rock, paper, or scissors): "
+            echo -n "Enter your move (rock, paper, or scissors) you have five seconds: "
             read -t 5 -r user_move
 
 
             if [[ -z "$user_move" ]]; then
-                echo "Time's up! You lose."
-                break
-            fi
+                echo -e "\n\e[31mTime's up! You lose.\e[0m"
+		continue
+	    fi
 
             # Validate the user's move
             if [[ "$user_move" != "rock" && "$user_move" != "paper" && "$user_move" != "scissors" ]]; then
-                echo "Invalid move. Please choose rock, paper, or scissors."
+                echo -e "\e[31mInvalid move, you lose!\e[0m"
                 continue
             fi
 
@@ -49,18 +39,18 @@ while true; do
 
             # Determine winner
             if [[ "$user_move" == "$computer_move" ]]; then
-                echo "It's a tie! Let's try again."
+                echo -e "\e[31mIt's a tie, but you didn't win XD\e[0m"
             elif [[ ("$user_move" == "rock" && "$computer_move" == "scissors") ||
                     ("$user_move" == "scissors" && "$computer_move" == "paper") ||
                     ("$user_move" == "paper" && "$computer_move" == "rock") ]]; then
-                echo "You win! You may exit now."
+                echo -e "\e[32mYou win! You may exit now.\e[0m"
                 exit 0
             else
-                echo "I win! You remain trapped. Try again."
+                echo -e "\e[31mI win! You remain trapped. Try again.\e[0m"
 	    fi
         done
     else
-	echo "no, try something else"
+	echo -e "\e[31mno, try something else\e[0m"
     fi
 
 done
